### PR TITLE
remove some [@bs.string] warning

### PR DESCRIPTION
**Pull request by lin2jie2**
remove some [@bs.string] waning

by default v12.1.4, in my case bs-platform: ^8.2.0, reason-react: ^0.9.1, reason-react-native: 0.62.3.
has some waning by [@bs.string] and cannot compiled(not generate ReactNativeSvg.bs.js) and cannot `open ReactNativeSvg`.

删除一些因[@bs.string]导致无法通过编译的警告。

Closes #<number-of-the-issue>

### CODE REVIEW

**Comment by lin2jie2** [comment]
my node version is v12.18.3
react version is :  16.13.1
react native version is: 0.63.3

**Comment by Freddy03h** [comment]
I've got the same issue on a bs-platform 8.3 project and used your branch, it work well!

**Comment by lin2jie2** [comment]
Glad to help you


很高兴对你有所帮助

**Comment by Freddy03h** [comment]
I think we can merge it, what do you think @MoOx ?
Should we also up bs-platform dependency to 8.2 ?
And, is it a breaking change and we should up the major version of this project ? But it wouldn't follow the version of react-native-svg anymore …

**Comment by lin2jie2** [comment]
Compatibility issues are not easy to deal with, I guess.
If you're not familiar with ReasonML, consider ReScript.
ReScript is more JavaScript oriented.

ReasonML is too hard for me.
Too much input for too little output.
Writing code is all guesswork.


兼容问题，不好处理吧。
如果你对ReasonML不太熟悉，可以考虑下ReScript。
ReScript更偏向JavaScript。

对我而言 ReasonML 太难了。
投入太多，产出太少。
写代码全靠猜。

**Comment by MoOx** [comment]
The reason the source without this change cannot be compiled is because some config issue we got (see https://github.com/reason-react-native/safe-area-context/pull/4).
I will address that first, then I will end up merging this PR as I will need it at some point in time. Thanks for the work & the thread !

**Comment by MoOx** [comment]
That said, any reason why the build isn't working? https://github.com/reason-react-native/svg/pull/5/checks?check_run_id=1209774591

**Comment by Freddy03h** [comment]
@MoOx I think we must up bs-platform to 8.2 before removing the [@bs.string]
```
  "devDependencies": {
    "bs-platform": "^8.0.0", -> "^8.2.0",
```

(in the lockfile of this project, bs-platform is)
```
bs-platform@^8.0.0:
  version "8.0.3"
```

**Comment by Freddy03h** [comment]
I think it's related to the comment I made in this project : https://github.com/reason-react-native/picker/commit/06d99baa8e48ba3b8903b0b8b88ff4da92287b05#commitcomment-43898968

**Comment by Freddy03h** [comment]
I think we can, at first, release a patch version for all packages with the new warning/error config.
And then release an other version (major ? minor ?) upgrading to 8.2 and resolving those warning like removing `[@bs.string]`.

**Comment by Freddy03h** [comment]
Hi @lin2jie2 !
Are this branch fix the warning/error on your project? https://github.com/reason-react-native/svg/pull/6

**Comment by lin2jie2** [comment]
i don’t know, I’m give up.
There are too many libraries are too old or out of dated.

**Comment by Freddy03h** [comment]
@MoOx pushed the fix to master, so you can try master

**Comment by MoOx** [comment]
Not relevant anymore.

**Pull request closed without merging**
