### PR TITLE
Add touch event props

### PR DESCRIPTION
**Pull request by reck753**
Hi!

I added the missing touch event props:
- `onPress`
- `onPressIn`
- `onPressOut`
- `onLongPress`
- `disabled`
- `delayPressIn`
- `delayPressOut`
- `delayLongPress`

https://github.com/react-native-svg/react-native-svg#touch-events

### CODE REVIEW

**Comment by MoOx** [comment]
Hi @reck753, thanks for this contribution! Could you adjust the onPress* to add the argument received (event).
It seems it's not correctly typed in the source https://github.com/react-native-svg/react-native-svg/blob/fa9a25d36b6f863d3148bdd5dd1ac76e91339402/src/ReactNativeSVG.web.ts#L18 but I am sure we could have something like `Event.pressEvent => unit` seems more accurate.

**Comment by reck753** [comment]
> Hi @reck753, thanks for this contribution! 

You are welcome!
I also adjusted the types for the `delay*` to `int` instead. I totally forgot that the value should be in `milliseconds` and that it doesn't make sense to be `float`. The type is `int` as well for RN pressables:
https://github.com/rescript-react-native/rescript-react-native/blob/e625be295df739f91f98b6e12855b4bcd7a6623d/src/components/TouchableOpacity.res#L23

**Comment by MoOx** [comment]
Thanks!

**Comment by MoOx** [comment]
Released in 12.1.8

**Pull request merged**
